title: WatsApp TV
description: Discover entertaining clips that capture the funny things that happen when people and animals are at their spontaneous best
url: http://www.watsapp.tv
date_format: '%B %d, %Y'
logo: watsapplogo.png
permalink: :title
tell: 18763078162
contact: '/contact/#wj-contact'
learn-more: '/about/#wj-features'
github: https://github.com
youtube: https://www.youtube.com/joinwatsapp

twitter:
  username: joinwatsapp
  
Instagram:
  username: joinwatsapp
  
Snapchat:
  username: joinwatsapp

social:
  name: joinwatsapp
  links:
    - https://twitter.com/joinwatsapp
    - https://facebook.com/joinwatsapp
    - https://snapchat.com/add/joinwatsapp
    - https://instagram.com/joinwatsapp


facebook:
 app_id: 549480635219583
 publisher: joinwatsapp
 admins: garen

include: ["_pages"]
exclude:
    - _extra


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

review:
  link: http://search.google.com/local/writereview?placeid=ChIJx113w8QUuzsR_3IiWBPrucE
  short-link: https://goo.gl/fAcxe9

review-link: 'https://www.google.com/search?q=Webjeda#lkt=LocalPoiReviews&lrd=0x3bbb14c4c3775dc7:0xc1b9eb13582272ff,3,5,,&trex=m_t:lcl_akp,rc_f:nav,rc_ludocids:13959446988327121663,rc_q:Webjeda,ru_q:Webjeda'


plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
