title: Allpree.comâ„¢ - Best Cashback Website in Jamaica
description: Allpree is the fastest-growing cashback website in Jamaica that provides you with amazing cashback deals to save more on every purchase. 
url: https://www.allpree.com
date_format: '%B %d, %Y'
logo: Allpree.jpg
permalink: :title
tell: 18762042132
chatgroup: KYGzNjlSqzx582yJFq7mYs
giveaway: iPhone 12 Pro MAX
contact: '/contact/#wj-contact'
learn-more: '/about/#wj-features'
github: https://github.com
youtube: https://www.youtube.com/

twitter:
  username: allpreedotcom 
  
Instagram:
  username: allpreedotcom
  
Snapchat:
  username: allpreedotcom
  
Tiktok:
   username: allpreedotcom

social:
  name: 
  links:
    - https://twitter.com/allpreedotcom
    - https://facebook.com/allpreedotcom
    - https://snapchat.com/add/allpreedotcom
    - https://instagram.com/allpreedotcom


facebook:
 app_id: 
 publisher: allpreedotcom
 admins: garen

include: ["_pages"]
exclude:
    - _extra


#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []


sass:
 style: compressed

review:
  link: http://search.google.com/local/writereview?placeid=ChIJx113w8QUuzsR_3IiWBPrucE
  short-link: https://goo.gl/fAcxe9

review-link: 'https://www.google.com/search?q=Webjeda#lkt=LocalPoiReviews&lrd=0x3bbb14c4c3775dc7:0xc1b9eb13582272ff,3,5,,&trex=m_t:lcl_akp,rc_f:nav,rc_ludocids:13959446988327121663,rc_q:Webjeda,ru_q:Webjeda'


plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-redirect-from
